export const errorCodes = {
  EMAIL_ALREADY_EXISTS: 'ERROR-001',
  DOCUMENT_NUMBER_ALREADY_EXISTS: 'ERROR-002',
  RESOURCE_NOT_FOUND: 'ERROR-003',
  RESOURCE_NOT_DAMAGED: 'ERROR-004',
  RESOURCE_UNDER_MAINTENANCE: 'ERROR-005',
  RESOURCE_ALREADY_FINISHED_MAINTENANCE: 'ERROR-006',
  PREVIOUS_MAINTENANCE_NOT_FINALIZED: 'ERROR-007',
  SERVICE_TYPE_ALREADY_EXISTS: 'ERROR-008',
  CONTACT_NAME_ALREADY_EXISTS: 'ERROR-009',
  RESOURCE_ALREADY_EXISTS: 'ERROR-010',
  WORKER_TYPE_ALREADY_EXISTS: 'ERROR-011',
  WORKER_TYPE_NOT_FOUND: 'ERROR-012',
} as const;
