export const errorCodes = {
  RESOURCE_NOT_FOUND: 'ERROR-003',
  RESOURCE_NOT_DAMAGED: 'ERROR-004',
  RESOURCE_UNDER_MAINTENANCE: 'ERROR-005',
  RESOURCE_ALREADY_FINISHED_MAINTENANCE: 'ERROR-006',
  PREVIOUS_MAINTENANCE_NOT_FINALIZED: 'ERROR-007',
} as const;
