name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Autentica en GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Configura gcloud con tu proyecto
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4. Fija la región por defecto para Cloud Run
      - name: Set default Cloud Run region
        run: gcloud config set run/region ${{ secrets.GCP_REGION }}

      # 5. Construye y publica la imagen con Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/level-music-app:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/${{ secrets.GCP_PROJECT_ID }}/level-music-app:latest
          cache-to: type=registry,mode=max,ref=gcr.io/${{ secrets.GCP_PROJECT_ID }}/level-music-app:latest

      # 6. Despliega en Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: level-music-app
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: ${{ secrets.GCP_REGION }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/level-music-app:${{ github.sha }}
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            FIREBASE_CREDENTIALS_PATH=${{ secrets.FIREBASE_SA_B64 }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}
            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
            GMAIL_USER=${{ secrets.GMAIL_USER }}
            GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}
